### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by domcleal** [bundlerext/bundler_ext#19]
Is the gem actively maintained?

Would you like some help?  I'd be willing to co-maintain to merge PRs (especially #18) , get tests running here and publish a new release if necessary.

**Comment by movitto** [comment]
Merged #18 and pushed 0.4.1 to rubygems.

Help would be appreciated. Feel free to request commit rights to the github repo

---

TLDR; yes :-)

**Comment by domcleal** [comment]
Thanks very much!

I don't think I can request it, but feel free to send an org invite if you'd like. I could probably sort out the tests and rspec.
